### ISSUE TITLE
attempting to build manylinux2014 erroring with "no acceptable C compiler found in $PATH"

### ISSUE THREAD

**Issue by Clockwork-Muse** [panda3d/buildbot-panda3d#4]
I've been doing my own builds of panda because I need egl enabled, which also means I need to build the relevant manylinux docker images to be able to build the panda wheels.  

I'm not sure what's changed, but I'm no longer able to build `manylinux2014` images.  Part of the issue is that builds aren't repeatable (it grabs the current head of the branch for panda3d/manylinux) - I can't successfully rebuild the image I'm currently using.  I _am_ able to build `manylinux2010` images with the same script, although note I'm forced to build the final application as `manylinux2014` due to other dependencies (namely opencv).

My (mostly) realized build script is this:
```shell
$ apk add --no-cache bash git
$ wget https://raw.githubusercontent.com/panda3d/buildbot-panda3d/${PANDA3D_MANYLINUX_COMMIT_SHA}/build_scripts/prepare_manylinux.sh
$ bash prepare_manylinux.sh manylinux2014-x86_64
$ cd manylinux
$ wget https://raw.githubusercontent.com/panda3d/buildbot-panda3d/${PANDA3D_MANYLINUX_COMMIT_SHA}/dockerfiles/manylinux2014-x86_64 -O docker/Dockerfile
$ docker build
   --pull
   --rm
   --tag ${CI_REGISTRY_IMAGE}/manylinux:manylinux2014-x86_64
   docker/
```
which eventually fails with:
```
configure: error: in `/libtool-2.4.6':
configure: error: no acceptable C compiler found in $PATH
```

Full (anonymized) build log is here:
[anonymized.log](https://github.com/panda3d/buildbot-panda3d/files/7313515/anonymized.log)

**Comment by Clockwork-Muse** [comment]
... I suppose my issue would be solved if the build images were published to a container registry, since then I wouldn't need to build them myself.
That aside, we're really feeling the pain of maintaining separate buildscripts, especially since the base repository migrated to a combined dockerfile back in January (no branch per platform/arch).

**Comment by Clockwork-Muse** [comment]
Okay, so, _in theory_ [something like this](https://github.com/Clockwork-Muse/buildbot-panda3d/tree/single_manylinux) should be fine, but there's a couple of issues currently:

- Tests from upstream have to be disabled if you're running docker-in-docker
- For some reason (regardless of whether the yum package or the manual download is used), there are duplicate definition errors in openal _when panda itself builds_.
- Others?  (haven't been getting past audio yet, although I can disable it for my purposes).
- I don't have anything with `buildbot` on it, so I'm guessing at those changes.

**Comment by rdb** [comment]
So, we nowadays just use the upstream manylinux2014 container, no need to build it yourself.  Our manylinux2014 dockerfile just directly derives from upstream:
https://github.com/panda3d/buildbot-panda3d/blob/master/dockerfiles/manylinux2014-x86_64

Is this issue moot now?

**Comment by Clockwork-Muse** [comment]
Issue is moot for me for other reasons now.

Shortly before you switched to basing off the upstream container my internal scripts did as well, although since you switched I'd probably try to build from that source instead now.

That said, it'd still be better if I didn't have to build my own copy of the image, but if instead the built image was published to a container repo (github gives you one, for instance).
There's also some potential minor tweaks that can be done to the script to decrease the overall image size (downloading the thirdparty zip during the `RUN` that also unpacks it, for instance, although care would need to be taken to allow cache busting as necessary), but getting an existing container would help more.

**Comment by rdb** [comment]
I'd be happy to consider it in principle, but I don't have the mindspace right now to investigate how to publish these containers, and do so in a robust and automatic manner.

You're right that we could decrease the size, a further optimization would be to download, unzip, build and then delete the build cache for the thirdparty packages in one step.  I've not made any attempt to do so so far, but I'll happily entertain a PR if you can do the work of updating and testing the dockerfile.

Closing the issue since it is moot as you say.
